### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sundowndev** [sundowndev/dorkgen#2]
- [x] .Intitle()
- [x] Rename .ToString() to .String()
- [x] Implement .QueryParams() to return URL-serialized params
- [x] Rename .ToURL() to .URL()
- [x] Change .Exclude() interface to receive struct pointer instead of string
- [x] Coverage
- [x] go doc
- [x] Implement And operator :  `&` or `+`
- [x] Update Or operator value : `|`
